services:
  - type: web
    name: stokapp
    env: python
    runtime: python3.8
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0 